### ISSUE TITLE
JAVA: a jni error has occurred please check your installation and try again

### ISSUE THREAD

**Issue by Speciesx** [paulwedeck/settlers-remake#36]
Can't run newer Version than [v0.5.3-alpha2](https://github.com/paulwedeck/settlers-remake/releases/tag/v0.5.3-alpha2)

![grafik](https://user-images.githubusercontent.com/1196375/160293728-68e63877-00d4-4220-8719-3a1a8836059b.png)
![grafik](https://user-images.githubusercontent.com/1196375/160293732-95b2f355-f364-4273-8f98-281016b89a7f.png)

Windows 10 x64
Java SE Runtime Environment 8.0 Update 321 x64

**Comment by paulwedeck** [comment]
Java 8 is too old. You need Java 11 or newer.

**Comment by Speciesx** [comment]
Java SE Runtime Environment 8.0 Update 321 x64 
This is the newest one, released in January 2022.

**Comment by paulwedeck** [comment]
Java SE Runtime Environment **8.0** is still too old even the newest version of 8.0 can't execute JSettlers while all release newer than Java 11 should be able run JSettlers.

I see that the download link in the read me is misleading because the page apparently no longer gets updated except for legacy versions like Java 8.

Oracle provides newer Java builds here: https://www.oracle.com/java/technologies/downloads/
or java builds by adopt openjdk: https://adoptopenjdk.net/
or by Amazon: https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/downloads-list.html
or by Microsoft: https://docs.microsoft.com/en-us/java/openjdk/download

It really doesn't depend where you download your Java version from as long as it is Java 11 or newer.

I will update the link in the read me as soon as I find a better link.

**Comment by Speciesx** [comment]
I know about the Java SE Development Kit, but most user like me have only Runtime Environment. I'm not a java developer, i don't need the java development tools and environment.

**Comment by paulwedeck** [comment]
From what I can see newer Java versions no longer offer a single JRE.
https://stackoverflow.com/questions/53733312/where-is-jre-11

**Comment by HiranChaudhuri** [comment]
@Speciesx If you are no java developer, not caring about the JRE or other installation details but still interested in running the varying builds of JSettlers have a look at https://github.com/HiranChaudhuri/settlers-installer.
